development: &default
  adapter: postgis
  schema_search_path: public
  database: geosharer_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: geosharer_test
